---
# PostgreSQL deployment
- hosts: all
  remote_user: centos
  sudo: yes
  roles:
    - { role: sfromm.postgresql }
  post_tasks:
    - name: Configure TCP/IP Client Authorizations
      lineinfile: dest=/var/lib/pgsql/data/postgresql.conf regexp=^listen_addresses line=listen_addresses='*'

    - name: Restart PostgreSQL
      service: name=postgresql state=restarted
